services:
  - type: web
    name: enterns-tech
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_NAME
        value: Enterns Tech
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: MENTOR_EMAIL
        sync: false
      - key: APP_BASE_URL
        sync: false
